# Generated by Django 5.2.5 on 2025-09-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedor', '0002_unidadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservistaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('run', models.PositiveIntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Retiro Temporal', 'Retiro Temporal')], max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='gestion_reserva/reservistas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('afp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.afpmodel')),
                ('arma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.armaserviciomodel')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.categoriamodel')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.ciudadmodel')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.estadocivilmodel')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.gradomodel')),
                ('grupo_sanguineo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.gruposanguineomodel')),
                ('isapre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.isapremodel')),
                ('profesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.profesionmodel')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.religionmodel')),
                ('uac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.uacmodel')),
                ('ubm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.ubmmodel')),
            ],
            options={
                'verbose_name': 'Reservista',
                'verbose_name_plural': 'Reservistas',
                'ordering': ['creado'],
            },
        ),
    ]
