# Generated by Django 5.2.5 on 2025-09-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0002_unidadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmodel',
            name='escalon_superior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
