# Generated by Django 5.2.5 on 2025-09-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedor', '0002_unidadmodel'),
        ('reservistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucionAscenso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resolucion', models.DateField()),
                ('numero_resolucion', models.CharField(max_length=100)),
                ('fecha_ascenso', models.DateField()),
                ('tipo_resolucion', models.CharField(choices=[('Ascenso', 'Ascenso'), ('Nombramiento', 'Nombramiento')], max_length=20)),
                ('resolucion', models.FileField(blank=True, null=True, upload_to='resoluciones_ascenso/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('grado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.gradomodel')),
                ('id_reservista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservistas.reservistamodel')),
            ],
            options={
                'verbose_name': 'Resolución de Ascenso',
                'verbose_name_plural': 'Resoluciones de Ascensos',
                'ordering': ['fecha_resolucion'],
            },
        ),
        migrations.CreateModel(
            name='ResolucionCambioEscalafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resolucion', models.DateField()),
                ('numero_resolucion', models.CharField(max_length=100)),
                ('resolucion', models.FileField(blank=True, null=True, upload_to='resoluciones_escalafon/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('Escalafon_destino', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='escalafon_destino', to='mantenedor.armaserviciomodel')),
                ('Escalafon_proveniente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Escalafon_proveniente', to='mantenedor.armaserviciomodel')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.gradomodel')),
                ('id_reservista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservistas.reservistamodel')),
            ],
            options={
                'verbose_name': 'Cambio de Escalafón',
                'verbose_name_plural': 'Cambios de Escalafones',
                'ordering': ['fecha_resolucion'],
            },
        ),
        migrations.CreateModel(
            name='ResolucionCambioInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resolucion', models.DateField()),
                ('numero_resolucion', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=50)),
                ('procedencia', models.CharField(choices=[('Ejercito', 'Ejercito'), ('Armada', 'Armada'), ('Fuerza Aerea', 'Fuerza Aerea')], max_length=50)),
                ('destino', models.CharField(choices=[('Ejercito', 'Ejercito'), ('Armada', 'Armada'), ('Fuerza Aerea', 'Fuerza Aerea')], max_length=50)),
                ('resolucion', models.FileField(blank=True, null=True, upload_to='resoluciones_institucion/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('id_reservista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservistas.reservistamodel')),
            ],
            options={
                'verbose_name': 'Cambio de institucion',
                'verbose_name_plural': 'Cambios de instituciones',
                'ordering': ['fecha_resolucion'],
            },
        ),
        migrations.CreateModel(
            name='ResolucionMedalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resolucion', models.DateField()),
                ('numero_resolucion', models.CharField(max_length=100)),
                ('fecha_otorgamiento', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('id_reservista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservistas.reservistamodel')),
                ('tipo_medalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.conedecoracionmodel')),
            ],
            options={
                'verbose_name': 'Resolución de Medalla',
                'verbose_name_plural': 'Resoluciones de Medallas',
                'ordering': ['fecha_resolucion'],
            },
        ),
    ]
